# .github/workflows/ci.yml

name: R3 CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test-linux:
    name: Test (Linux)
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: r3_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: List installed packages
      run: npm list
    
    - name: Run tests with verbose output
      run: npm test -- --verbose
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/r3_test
        REDIS_URL: redis://localhost:6379
        NODE_ENV: test

  test-windows:
    name: Test (Windows Build)
    runs-on: ubuntu-latest   # Changed to Linux runner for container support
    
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: r3_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
      
    - name: Generate Prisma Client
      run: npx prisma generate

    - name: Run tests with verbose output
      run: npm test -- --verbose
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/r3_test
        REDIS_URL: redis://localhost:6379
        NODE_ENV: test

    - name: Create Windows setup script
      if: github.ref == 'refs/heads/main'
      run: |
        cat > setup-windows.bat << 'EOL'
        @echo off
        echo Setting up R3 System...
        docker compose up -d
        npm install
        npx prisma generate
        npx prisma db push
        echo Setup complete! Run 'npm run dev' to start the application.
        EOL

    - name: Upload Windows setup artifacts
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v3
      with:
        name: windows-setup
        path: |
          setup-windows.bat
          docker/docker-compose.yml
          docker/docker-compose-test.txt
          docker/docker-compose-prod.txt
          package.json
          package-lock.json

  build-and-push:
    needs: [test-linux, test-windows]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Add this step to debug permissions
      - name: Debug token permissions
        run: |
          echo "Token has these scopes:"
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/user

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/r3:latest
          labels: ${{ steps.meta.outputs.labels }}